config/routes.rb
Rails.application.routes.draw do


  resources :insurers
  resources :serviceproviders
  resources :rhospitals
  resources :hospitals
  get 'dispatcherdash/index'

  get 'messages/create'

  get 'conversations/index'

  get 'conversation/index'

  get 'dashboard/index'

  get 'medevaccases/dispatcherindex'

  get 'medevaccases/dispatcheropencases'

  get 'medevaccases/opencases'

  get 'medevaccases/closedcases'

  get 'medevaccases/distribution'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :medevaccases
  resources :patients
  resources :conversations do
    resources :messages
    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash

    end
  end
  get 'users/gravatar'

  root 'static_pages#home'
  get  '/help',     to: 'static_pages#help'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/register', to: 'users#new'
end

app/models/accompanyingperson.rb
class Accompanyingperson < ApplicationRecord

  belongs_to :medevaccase
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casenote.rb
class Casenote < ApplicationRecord
  belongs_to :medevaccase
end

app/models/contactperson.rb
class Contactperson < ApplicationRecord
  belongs_to :medevaccase
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :medevaccases
end

app/models/insurer.rb
class Insurer < ApplicationRecord
  has_many :vettinginfos, inverse_of: :insurer, :dependent => :destroy
  accepts_nested_attributes_for :vettinginfos, reject_if: :all_blank, allow_destroy: true
end

app/models/medevaccase.rb
class Medevaccase < ApplicationRecord
  belongs_to :user
  has_many :patients, inverse_of: :medevaccase, :dependent => :destroy
  has_many :accompanyingpeople, inverse_of: :medevaccase, :dependent => :destroy
  has_many :contactpeople, inverse_of: :medevaccase, :dependent => :destroy
  has_many :stakeholders, inverse_of: :medevaccase, :dependent => :destroy
  has_many :casenotes, inverse_of: :medevaccase, :dependent => :destroy
  belongs_to :hospital
  belongs_to :rhospital
  accepts_nested_attributes_for :patients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :accompanyingpeople, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contactpeople, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :stakeholders, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :casenotes, reject_if: :all_blank, allow_destroy: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :medevaccase
end

app/models/pvettinginfo.rb
class Pvettinginfo < ApplicationRecord
  belongs_to :serviceprovider
end

app/models/rhospital.rb
class Rhospital < ApplicationRecord
  has_many :medevaccases
end

app/models/serviceportfolio.rb
class Serviceportfolio < ApplicationRecord
  belongs_to :serviceprovider
end

app/models/serviceprovider.rb
class Serviceprovider < ApplicationRecord

  has_many :serviceportfolios, inverse_of: :serviceprovider, :dependent => :destroy
  has_many :pvettinginfos, inverse_of: :serviceprovider, :dependent => :destroy
  accepts_nested_attributes_for :serviceportfolios, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :pvettinginfos, reject_if: :all_blank, allow_destroy: true
end

app/models/stakeholder.rb
class Stakeholder < ApplicationRecord
  belongs_to :medevaccase
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end

  has_many :medevaccases
end

app/models/vettinginfo.rb
class Vettinginfo < ApplicationRecord
  belongs_to :insurer

end

app/controllers/serviceproviders_controller.rb
class ServiceprovidersController < ApplicationController
  before_action :set_serviceprovider, only: [:show, :edit, :update, :destroy]

  # GET /serviceproviders
  # GET /serviceproviders.json
  def index
    @serviceproviders = Serviceprovider.all
  end

  # GET /serviceproviders/1
  # GET /serviceproviders/1.json
  def show
  end

  # GET /serviceproviders/new
  def new
    @serviceprovider = Serviceprovider.new
  end

  # GET /serviceproviders/1/edit
  def edit
  end

  # POST /serviceproviders
  # POST /serviceproviders.json
  def create
    @serviceprovider = Serviceprovider.new(serviceprovider_params)

    respond_to do |format|
      if @serviceprovider.save
        format.html { redirect_to @serviceprovider, notice: 'Serviceprovider was successfully created.' }
        format.json { render :show, status: :created, location: @serviceprovider }
      else
        format.html { render :new }
        format.json { render json: @serviceprovider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /serviceproviders/1
  # PATCH/PUT /serviceproviders/1.json
  def update
    respond_to do |format|
      if @serviceprovider.update(serviceprovider_params)
        format.html { redirect_to @serviceprovider, notice: 'Serviceprovider was successfully updated.' }
        format.json { render :show, status: :ok, location: @serviceprovider }
      else
        format.html { render :edit }
        format.json { render json: @serviceprovider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /serviceproviders/1
  # DELETE /serviceproviders/1.json
  def destroy
    @serviceprovider.destroy
    respond_to do |format|
      format.html { redirect_to serviceproviders_url, notice: 'Serviceprovider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serviceprovider
      @serviceprovider = Serviceprovider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def serviceprovider_params
      params.require(:serviceprovider).permit(:name, :companyalias,:address, :email, :phone, :contactperson,
                                              :entitysactive,
                                              serviceportfolios_attributes: [:name, :description, :_destroy],
                                              pvettinginfos_attributes: [:id, :heading, :notes, :_destroy])
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/insurers_helper.rb
module InsurersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rhospitals_helper.rb
module RhospitalsHelper
end

app/helpers/serviceproviders_helper.rb
module ServiceprovidersHelper
end

app/helpers/users_helper.rb
module UsersHelper


  def dispatcher
    current_user.dispatcher?
  end
end

app/views/serviceproviders/_form.html.erb
<%= form_with(model: serviceprovider, local: true) do |f| %>
  <% if serviceprovider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(serviceprovider.errors.count, "error") %> prohibited this serviceprovider from being saved:</h2>

      <ul>
      <% serviceprovider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :serviceprovider_name %>
  </div>

  <div class="field">
    <%= f.label "Company Alias" %>
    <%= f.text_field :companyalias, id: :serviceprovider_companyalias %>
  </div>


  <div class="field">
    <%= f.label "Status" %>
    <%= f.text_field :entityactive, id: :serviceprovider_entityactive %>
  </div>


  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address, id: :serviceprovider_address %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, id: :serviceprovider_email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone, id: :serviceprovider_phone %>
  </div>

  <div class="services-details ">
    <%= f.fields_for :serviceportfolios do |portfolio| %>

      <%= render 'serviceportfolio_fields', :f => portfolio %>

    <% end %>
    <div class = "links">
      <%= link_to_add_association 'Add Service', f, :serviceportfolios %>
      <p class="count">Total: <span><%= @serviceprovider.serviceportfolios.count %></span></p>
    </div>
  </div>

  <div class="services-details ">
    <%= f.fields_for :pvettinginfos do |info| %>

      <%= render 'pvettinginfo_fields', :f => info %>

    <% end %>
    <div class = "links">
      <%= link_to_add_association 'Add Vetting Item', f, :pvettinginfos %>
      <p class="count">Total: <span><%= @serviceprovider.pvettinginfos.count %></span></p>
    </div>
  </div>

  <div class="field">
    <%= f.label :contactperson %>
    <%= f.text_field :contactperson, id: :serviceprovider_contactperson %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/serviceproviders/_pvettinginfo_fields.html.erb
<div class="nested-fields">

  <div class = "field">
    <%= f.label  "Heading:"  %>
    <%= f.text_field :heading %>
  </div>

  <div class = "field">
    <%= f.label "Notes:" %>
    <%= f.text_field :notes %>
  </div>


  <%= link_to_remove_association 'Remove Vetting Item', f %>


</div>

app/views/serviceproviders/_serviceportfolio_fields.html.erb
<div class="nested-fields">

  <div class = "field">
    <%= f.label  "name:"  %>
    <%= f.text_field :name %>
  </div>

  <div class = "field">
    <%= f.label "Description:" %>
    <%= f.text_area :description %>
  </div>


  <%= link_to_remove_association 'Remove Service', f %>


</div>

app/views/serviceproviders/edit.html.erb
<% provide(:title, "Providers") %>

<h2>Editing Service Provider</h2>

<%= render 'form', serviceprovider: @serviceprovider %>

<%= link_to 'Show', @serviceprovider %> |
<%= link_to 'Back', serviceproviders_path %>

app/views/serviceproviders/index.html.erb
<% provide(:title, "Providers") %>
<p id="notice"><%= notice %></p>

<h2>Service Providers</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company Alias</th>
      <th>Active</th>
      <th>Address</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Services</th>
      <th>Contactperson</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @serviceproviders.each do |serviceprovider| %>
      <tr>
        <td><%= serviceprovider.name %></td>
        <td><%= serviceprovider.companyalias %></td>
        <td><%= serviceprovider.entityactive %></td>
        <td><%= serviceprovider.address %></td>
        <td><%= serviceprovider.email %></td>
        <td><%= serviceprovider.phone %></td>
        <td><%= serviceprovider.services %></td>
        <td><%= serviceprovider.contactperson %></td>
        <td><%= link_to 'View', serviceprovider %></td>
        <td><%= link_to 'Edit', edit_serviceprovider_path(serviceprovider) %></td>
        <td><%= link_to 'Delete', serviceprovider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<hr/>

<%= link_to 'New Service Provider', new_serviceprovider_path %><br/>
<%= link_to 'Dashboard', dashboard_index_path %>

app/views/serviceproviders/new.html.erb
<h1>New Serviceprovider</h1>

<%= render 'form', serviceprovider: @serviceprovider %>

<%= link_to 'Back', serviceproviders_path %>

app/views/serviceproviders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @serviceprovider.name %>
</p>

<p>
  <strong>Company Alias:</strong>
  <%= @serviceprovider.companyalias %>
</p>

<p>
  <strong>Status:</strong>
  <%= @serviceprovider.entityactive %>
</p>

<p>
  <strong>Address:</strong>
  <%= @serviceprovider.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @serviceprovider.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @serviceprovider.phone %>
</p>

<% for serviceportfolio in @serviceprovider.serviceportfolios %>
  <p>
    <strong>[Service] Name:</strong>
    <%=h serviceportfolio.name %>
  </p>

  <p>
    <strong>[Service] Description:</strong>
    <textarea rows="4" cols="50" readonly>
      <%=h serviceportfolio.description %>
    </textarea>
  </p>

<hr/>

<% end %>

<% for pvettinginfo in @serviceprovider.pvettinginfos %>
  <p>
    <strong> [Vetting] Heading:</strong>
    <%=h pvettinginfo.heading %>
  </p>

  <p>
    <strong>[Vetting] Notes:</strong>
    <textarea rows="4" cols="50" readonly>
      <%=h pvettinginfo.notes %>
    </textarea>
  </p>


<% end %>


  <p>
    <strong>Contactperson:</strong>
    <%= @serviceprovider.contactperson %>
  </p>

<%= link_to 'Edit', edit_serviceprovider_path(@serviceprovider) %> |
<%= link_to 'Back', serviceproviders_path %>