config/routes.rb
Rails.application.routes.draw do


  resources :insurers
  resources :serviceproviders
  resources :rhospitals
  resources :hospitals
  get 'dispatcherdash/index'

  get 'messages/create'

  get 'conversations/index'

  get 'conversation/index'

  get 'dashboard/index'

  get 'medevaccases/dispatcherindex'

  get 'medevaccases/dispatcheropencases'

  get 'medevaccases/opencases'

  get 'medevaccases/closedcases'

  get 'medevaccases/distribution'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :medevaccases
  resources :patients
  resources :conversations do
    resources :messages
    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash

    end
  end
  get 'users/gravatar'

  root 'static_pages#home'
  get  '/help',     to: 'static_pages#help'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/register', to: 'users#new'
end

app/models/accompanyingperson.rb
class Accompanyingperson < ApplicationRecord

  belongs_to :medevaccase
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casenote.rb
class Casenote < ApplicationRecord
  belongs_to :medevaccase
end

app/models/contactperson.rb
class Contactperson < ApplicationRecord
  belongs_to :medevaccase
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :medevaccases
end

app/models/insurer.rb
class Insurer < ApplicationRecord
  has_many :vettinginfos, inverse_of: :insurer, :dependent => :destroy
  accepts_nested_attributes_for :vettinginfos, reject_if: :all_blank, allow_destroy: true
end

app/models/medevaccase.rb
class Medevaccase < ApplicationRecord
  belongs_to :user
  has_many :patients, inverse_of: :medevaccase, :dependent => :destroy
  has_many :accompanyingpeople, inverse_of: :medevaccase, :dependent => :destroy
  has_many :contactpeople, inverse_of: :medevaccase, :dependent => :destroy
  has_many :stakeholders, inverse_of: :medevaccase, :dependent => :destroy
  has_many :casenotes, inverse_of: :medevaccase, :dependent => :destroy
  belongs_to :hospital
  belongs_to :rhospital
  accepts_nested_attributes_for :patients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :accompanyingpeople, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contactpeople, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :stakeholders, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :casenotes, reject_if: :all_blank, allow_destroy: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :medevaccase
end

app/models/pvettinginfo.rb
class Pvettinginfo < ApplicationRecord
  belongs_to :serviceprovider
end

app/models/rhospital.rb
class Rhospital < ApplicationRecord
  has_many :medevaccases
end

app/models/serviceportfolio.rb
class Serviceportfolio < ApplicationRecord
  belongs_to :serviceprovider
end

app/models/serviceprovider.rb
class Serviceprovider < ApplicationRecord

  has_many :serviceportfolios, inverse_of: :serviceprovider, :dependent => :destroy
  has_many :pvettinginfos, inverse_of: :serviceprovider, :dependent => :destroy
  accepts_nested_attributes_for :serviceportfolios, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :pvettinginfos, reject_if: :all_blank, allow_destroy: true
end

app/models/stakeholder.rb
class Stakeholder < ApplicationRecord
  belongs_to :medevaccase
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end

  has_many :medevaccases
end

app/models/vettinginfo.rb
class Vettinginfo < ApplicationRecord
  belongs_to :insurer

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/insurers_helper.rb
module InsurersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rhospitals_helper.rb
module RhospitalsHelper
end

app/helpers/users_helper.rb
module UsersHelper


  def dispatcher
    current_user.dispatcher?
  end
end

app/views/dashboard/index.html.erb
<% provide(:title, "Dashboard") %>


<hr />
<% if current_user.dispatcher == true %>
  <h2>My Dashboard</h2>
  <h2>[[i]] Dispatcher</h2>
<hr />
  <% if current_user.admin == true %>
    <strong><p class="alert">[[i]] Admin</p></strong>
  <% else %>
    <strong><p class="alert">[[i]] Non-Admin</p></strong>
  <% end %>
<hr />
  <ul class="nav navbar-nav navbar-right">



  </ul>

  <div class = "vertical-menu">
    <li><%= link_to "Directories", '#'%></li>
    <li><%= link_to "CaseMails", all_conversations_path %></li>
    <li><%= link_to "Hospitals", hospitals_path %></li>
    <li><%= link_to "Medevac Cases [All]", medevaccases_dispatcherindex_url %></li>
    <li><%= link_to "Open Cases", medevaccases_dispatcheropencases_path %></li>
    <li><%= link_to "Closed Cases", medevaccases_dispatcheropencases_path %></li>
    <li><%= link_to "Provider Posts", '#' %></li>
    <% if current_user.admin == true %>
      <li><%= link_to "Administration Area", rails_admin_path %></li>
      <li><%= link_to "Rhospitals", rhospitals_path %></li>
      <li><%= link_to "Service Providers", serviceproviders_path %></li>
      <li><%= link_to "Insurers", insurers_path %></li>
    <% end %>

    <% if current_user.clientadmin == true %>
      <li><%= link_to "Management View", medevaccases_distribution_path %></li>
    <% end %>

  </div>

<% else %>
  <h2>My Dashboard</h2>
  <hr />
  <ul class="nav navbar-nav navbar-right">

  </ul>
    <div>

    <hr />
      <div class = "vertical-menu">
        <li><%= link_to "Open New-Case", new_medevaccase_path %></li>
        <li><%= link_to "View Closed Cases", '#'%></li>
        <li><%= link_to "CaseMails", all_conversations_path %></li>
        <li><%= link_to "Hospitals", hospitals_path %></li>
        <li><%= link_to "Medevac Cases [All]", medevaccases_path %></li>
        <li><%= link_to "Provider Posts",'#' %></li>
        <li><%= link_to "Directories", '#' %></li>
        <li><%= link_to "Open Cases", medevaccases_opencases_path %></li>
        <li><%= link_to "Closed Cases", medevaccases_closedcases_path %></li>
        <% if current_user.clientadmin == true %>
          <li><%= link_to "Management View", medevaccases_distribution_path %></li>
        <% end %>
      </div>
    <hr />
  </div>

<% end %>