config/routes.rb
Rails.application.routes.draw do


  resources :insurers
  resources :serviceproviders
  resources :rhospitals
  resources :hospitals
  get 'dispatcherdash/index'

  get 'messages/create'

  get 'conversations/index'

  get 'conversation/index'

  get 'dashboard/index'

  get 'medevaccases/dispatcherindex'

  get 'medevaccases/dispatcheropencases'

  get 'medevaccases/opencases'

  get 'medevaccases/closedcases'

  get 'medevaccases/distribution'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :medevaccases
  resources :patients
  resources :conversations do
    resources :messages
    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash

    end
  end
  get 'users/gravatar'

  root 'static_pages#home'
  get  '/help',     to: 'static_pages#help'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/register', to: 'users#new'
end

app/models/accompanyingperson.rb
class Accompanyingperson < ApplicationRecord

  belongs_to :medevaccase
end

app/models/casenote.rb
class Casenote < ApplicationRecord
  belongs_to :medevaccase
end

app/models/contactperson.rb
class Contactperson < ApplicationRecord
  belongs_to :medevaccase
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :medevaccases
end

app/models/insurer.rb
class Insurer < ApplicationRecord
  has_many :vettinginfos, inverse_of: :insurer, :dependent => :destroy
  accepts_nested_attributes_for :vettinginfos, reject_if: :all_blank, allow_destroy: true
end

app/models/medevaccase.rb
class Medevaccase < ApplicationRecord
  belongs_to :user
  has_many :patients, inverse_of: :medevaccase, :dependent => :destroy
  has_many :accompanyingpeople, inverse_of: :medevaccase, :dependent => :destroy
  has_many :contactpeople, inverse_of: :medevaccase, :dependent => :destroy
  has_many :stakeholders, inverse_of: :medevaccase, :dependent => :destroy
  has_many :casenotes, inverse_of: :medevaccase, :dependent => :destroy
  belongs_to :hospital
  belongs_to :rhospital
  accepts_nested_attributes_for :patients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :accompanyingpeople, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contactpeople, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :stakeholders, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :casenotes, reject_if: :all_blank, allow_destroy: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :medevaccase
end

app/models/pvettinginfo.rb
class Pvettinginfo < ApplicationRecord
  belongs_to :serviceprovider
end

app/models/rhospital.rb
class Rhospital < ApplicationRecord
  has_many :medevaccases
end

app/models/serviceportfolio.rb
class Serviceportfolio < ApplicationRecord
  belongs_to :serviceprovider
end

app/models/serviceprovider.rb
class Serviceprovider < ApplicationRecord

  has_many :serviceportfolios, inverse_of: :serviceprovider, :dependent => :destroy
  has_many :pvettinginfos, inverse_of: :serviceprovider, :dependent => :destroy
  accepts_nested_attributes_for :serviceportfolios, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :pvettinginfos, reject_if: :all_blank, allow_destroy: true
end

app/models/stakeholder.rb
class Stakeholder < ApplicationRecord
  belongs_to :medevaccase
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end

  has_many :medevaccases
end

app/models/vettinginfo.rb
class Vettinginfo < ApplicationRecord
  belongs_to :insurer

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations.paginate(:page => params[:page], :per_page => 4)
  end

  def inbox
    @conversations = current_user.mailbox.inbox.paginate(:page => params[:page], :per_page => 4)
    render action: :index
  end

  def sent
    @conversations = current_user.mailbox.sentbox.paginate(:page => params[:page], :per_page => 4)
    render action: :index
  end

  def trash
    @conversations = current_user.mailbox.trash.paginate(:page => params[:page], :per_page => 4)
    render action: :index
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.mark_as_read(current_user)
    @message = Mailboxer::Message.new
  end

  def create
    @recipient = User.where(id: params[:user_ids])
    receipt = current_user.send_message(@recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end

  def new
    @recipients = User.all - [current_user]
    @conversation = Mailboxer::Conversation.new
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/insurers_helper.rb
module InsurersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rhospitals_helper.rb
module RhospitalsHelper
end

app/helpers/users_helper.rb
module UsersHelper


  def dispatcher
    current_user.dispatcher?
  end
end

app/views/conversations/index.html.erb
<h2>My CaseMails [All]</h2>


<hr />

| inbox (<%= current_user.mailbox.inbox.unread(current_user).count %>) |
All CaseMails (<%= current_user.mailbox.conversations.count %>) |
CaseMails Sent (<%= current_user.mailbox.sentbox.count %>) |


<hr />

<strong>Total: <%= @conversations.count %></strong>


<% @conversations.each do |conversation| %>
  <div>
    <% if conversation.is_unread?(current_user) %>
      <strong><%= link_to conversation.subject, conversation_path(conversation) %></strong>
    <% else %>
      <%= link_to conversation.subject, conversation_path(conversation) %>
    <% end %>
  </div>
<% end %>

<hr />
  <%= will_paginate @conversations %>
<hr />

<%= link_to "CaseMails [All]", all_conversations_path, class: "btn btn-primary" %>
<%= link_to "New CaseMail", new_conversation_path, class: "btn btn-primary" %>
<%= link_to "Inbox", inbox_conversations_path, class: "btn btn-primary" %>
<%= link_to "Dashboard", dashboard_index_path, class: "btn btn-danger" %>

app/views/conversations/new.html.erb
<h2>(CaseMail) New Case Conversation </h2>

<%= form_tag conversations_path, method: :post do %>

  <div>
    <%= select_tag :user_ids, options_from_collection_for_select(@recipients, :id, :email), multiple: true,
                   :required => 'required' %>
  </div>

  <div>
    <%= text_field_tag :subject, nil, placeholder: "Subject", :required => 'required' %>
  </div>

  <div>
    <%= text_area_tag :body, nil, placeholder: "Comment" , :required => 'required' %>
  </div>

  <hr />
  <%= submit_tag %>

  <%=link_to "CaseMails [All]", all_conversations_path, class: "btn btn-primary" %>

<% end %>

app/views/conversations/show.html.erb
<h2>Subject:</h2><h2><%= @conversation.subject %></h2>
<hr />
<h5>From:</h5>
<hr />
<%= current_user.email %>


<hr />
<h5>To:</h5>
<hr />
<% @conversation.participants.each do |participant| %>
  <div>
    <%= participant.email %>
  </div>
<% end %>

<hr />


<% @conversation.receipts_for(current_user).each do |receipt| %>
<div>
 <div><%= receipt.message.sender.email%> Wrote:</div>
  <p><%= receipt.message.body %></p>

  <% if receipt.message.attachment? %>
  <strong>Attached File</strong>
    <%= link_to receipt.message.attachment.file.filename, receipt.message.attachment.url, target: :blank %>
  <% end %>
</div>
<% end %>

<hr />
<h5>New CaseMail:</h5>
<hr />

<%= form_for @message, url: conversation_messages_path(@conversation) do |f| %>
  <div>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.file_field :attachment %>
  </div>
<hr />
  <%= f.submit %>

<% end %>
<hr />
<%=link_to "CaseMails [All]", all_conversations_path, class: "btn btn-primary" %>
<%= link_to "Inbox", inbox_conversations_path, class: "btn btn-primary" %>