config/routes.rb
Rails.application.routes.draw do


  resources :insurers
  resources :serviceproviders
  resources :rhospitals
  resources :hospitals
  get 'dispatcherdash/index'

  get 'messages/create'

  get 'conversations/index'

  get 'conversation/index'

  get 'dashboard/index'

  get 'medevaccases/dispatcherindex'

  get 'medevaccases/dispatcheropencases'

  get 'medevaccases/opencases'

  get 'medevaccases/closedcases'

  get 'medevaccases/distribution'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :medevaccases
  resources :patients
  resources :conversations do
    resources :messages
    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash

    end
  end
  get 'users/gravatar'

  root 'static_pages#home'
  get  '/help',     to: 'static_pages#help'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/register', to: 'users#new'
end

app/models/accompanyingperson.rb
class Accompanyingperson < ApplicationRecord

  belongs_to :medevaccase
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casenote.rb
class Casenote < ApplicationRecord
  belongs_to :medevaccase
end

app/models/contactperson.rb
class Contactperson < ApplicationRecord
  belongs_to :medevaccase
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :medevaccases
end

app/models/insurer.rb
class Insurer < ApplicationRecord
  has_many :vettinginfos, inverse_of: :insurer, :dependent => :destroy
  accepts_nested_attributes_for :vettinginfos, reject_if: :all_blank, allow_destroy: true
end

app/models/medevaccase.rb
class Medevaccase < ApplicationRecord
  belongs_to :user
  has_many :patients, inverse_of: :medevaccase, :dependent => :destroy
  has_many :accompanyingpeople, inverse_of: :medevaccase, :dependent => :destroy
  has_many :contactpeople, inverse_of: :medevaccase, :dependent => :destroy
  has_many :stakeholders, inverse_of: :medevaccase, :dependent => :destroy
  has_many :casenotes, inverse_of: :medevaccase, :dependent => :destroy
  belongs_to :hospital
  belongs_to :rhospital
  accepts_nested_attributes_for :patients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :accompanyingpeople, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contactpeople, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :stakeholders, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :casenotes, reject_if: :all_blank, allow_destroy: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :medevaccase
end

app/models/pvettinginfo.rb
class Pvettinginfo < ApplicationRecord
  belongs_to :serviceprovider
end

app/models/rhospital.rb
class Rhospital < ApplicationRecord
  has_many :medevaccases
end

app/models/serviceportfolio.rb
class Serviceportfolio < ApplicationRecord
  belongs_to :serviceprovider
end

app/models/serviceprovider.rb
class Serviceprovider < ApplicationRecord

  has_many :serviceportfolios, inverse_of: :serviceprovider, :dependent => :destroy
  has_many :pvettinginfos, inverse_of: :serviceprovider, :dependent => :destroy
  accepts_nested_attributes_for :serviceportfolios, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :pvettinginfos, reject_if: :all_blank, allow_destroy: true
end

app/models/stakeholder.rb
class Stakeholder < ApplicationRecord
  belongs_to :medevaccase
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end

  has_many :medevaccases
end

app/models/vettinginfo.rb
class Vettinginfo < ApplicationRecord
  belongs_to :insurer

end

app/controllers/insurers_controller.rb
class InsurersController < ApplicationController
  before_action :set_insurer, only: [:show, :edit, :update, :destroy]

  # GET /insurers
  # GET /insurers.json
  def index
    @insurers = Insurer.all
  end

  # GET /insurers/1
  # GET /insurers/1.json
  def show
  end

  # GET /insurers/new
  def new
    @insurer = Insurer.new
  end

  # GET /insurers/1/edit
  def edit
  end

  # POST /insurers
  # POST /insurers.json
  def create
    @insurer = Insurer.new(insurer_params)

    respond_to do |format|
      if @insurer.save
        format.html { redirect_to @insurer, notice: 'Insurer was successfully created.' }
        format.json { render :show, status: :created, location: @insurer }
      else
        format.html { render :new }
        format.json { render json: @insurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurers/1
  # PATCH/PUT /insurers/1.json
  def update
    respond_to do |format|
      if @insurer.update(insurer_params)
        format.html { redirect_to @insurer, notice: 'Insurer was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurer }
      else
        format.html { render :edit }
        format.json { render json: @insurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurers/1
  # DELETE /insurers/1.json
  def destroy
    @insurer.destroy
    respond_to do |format|
      format.html { redirect_to insurers_url, notice: 'Insurer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurer
      @insurer = Insurer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurer_params
      params.require(:insurer).permit(:name, :companyalias, :address, :email, :phone, :contactperson, :active,
                                      vettinginfos_attributes: [:id, :heading, :notes, :_destroy] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Medevacsoft'
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/insurers_helper.rb
module InsurersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rhospitals_helper.rb
module RhospitalsHelper
end

app/helpers/users_helper.rb
module UsersHelper


  def dispatcher
    current_user.dispatcher?
  end
end

app/views/insurers/_form.html.erb
<%= form_with(model: insurer, local: true) do |f| %>
  <% if insurer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insurer.errors.count, "error") %> prohibited this insurer from being saved:</h2>

      <ul>
      <% insurer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :insurer_name %>
  </div>

  <div class="field">
    <%= f.label :companyalias %>
    <%= f.text_field :companyalias, id: :insurer_companyalias %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address, id: :insurer_address %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, id: :insurer_email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone, id: :insurer_phone %>
  </div>

  <div class="field">
    <%= f.label :contactperson %>
    <%= f.text_field :contactperson, id: :insurer_contactperson %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active, id: :insurer_active %>
  </div>


  <div class="services-details ">
    <%= f.fields_for :vettinginfos do |vetting| %>

      <%= render 'vettinginfo_fields', :f => vetting %>

    <% end %>
    <div class = "links">
      <%= link_to_add_association 'Add Vetting Item', f, :vettinginfos %>
      <p class="count">Total: <span><%= @insurer.vettinginfos.count %></span></p>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insurers/_vettinginfo_fields.html.erb
<div class="nested-fields">

  <div class = "field">
    <%= f.label  "Heading:"  %>
    <%= f.text_field :heading %>
  </div>

  <div class = "field">
    <%= f.label "Notes:" %>
    <%= f.text_area :notes %>
  </div>


  <%= link_to_remove_association 'Remove Vetting Item', f %>


</div>

app/views/insurers/edit.html.erb
<h1>Editing Insurer</h1>

<%= render 'form', insurer: @insurer %>

<%= link_to 'Show', @insurer %> |
<%= link_to 'Back', insurers_path %>

app/views/insurers/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Insurers</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Companyalias</th>
      <th>Address</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Contactperson</th>
      <th>active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurers.each do |insurer| %>
      <tr>
        <td><%= insurer.name %></td>
        <td><%= insurer.companyalias %></td>
        <td><%= insurer.address %></td>
        <td><%= insurer.email %></td>
        <td><%= insurer.phone %></td>
        <td><%= insurer.contactperson %></td>
        <td><%= insurer.active %></td>
        <td><%= link_to 'View', insurer %></td>
        <td><%= link_to 'Edit', edit_insurer_path(insurer) %></td>
        <td><%= link_to 'Delete', insurer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<hr/>

<%= link_to 'New Insurer', new_insurer_path %><br/>

<%= link_to 'Dashboard', dashboard_index_path %>

app/views/insurers/new.html.erb
<h1>New Insurer</h1>

<%= render 'form', insurer: @insurer %>

<%= link_to 'Back', insurers_path %>

app/views/insurers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @insurer.name %>
</p>

<p>
  <strong>Companyalias:</strong>
  <%= @insurer.companyalias %>
</p>

<p>
  <strong>Address:</strong>
  <%= @insurer.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @insurer.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @insurer.phone %>
</p>

<p>
  <strong>Contactperson:</strong>
  <%= @insurer.contactperson %>
</p>

<p>
  <strong>active:</strong>
  <%= @insurer.active %>
</p>

<%= link_to 'Edit', edit_insurer_path(@insurer) %> |
<%= link_to 'Back', insurers_path %>